# Generated by Django 3.0.5 on 2020-04-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrelation',
            name='canChangeCow',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
